// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generate the sidebar from the docs folder
  documentationSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],
};

export default sidebars;
